import requests

moedas = {
    "BRL": "Real brasileiro",
    "AED": "Dirham dos Emirados Árabes Unidos",
    "AFN": "Afegane afegão",
    "ALL": "Lek albanês",
    "AMD": "Dram armênio",
    "ANG": "Florim das Antilhas Holandesas",
    "AOA": "Kwanza angolano",
    "ARS": "Peso argentino",
    "AUD": "Dólar australiano",
    "AWG": "Florim de Aruba",
    "AZN": "Manat azeri",
    "BAM": "Marco conversível bósnio",
    "BBD": "Dólar de Barbados",
    "BDT": "Taka de Bangladesh",
    "BGN": "Lev búlgaro",
    "BHD": "Dinar bareinita",
    "BIF": "Franco burundês",
    "BMD": "Dólar bermudense",
    "BND": "Dólar de Brunei",
    "BOB": "Boliviano",
    "BSD": "Dólar bahamense",
    "BTN": "Ngultrum butanês",
    "BWP": "Pula botsuano",
    "BYN": "Rublo bielorrusso",
    "BZD": "Dólar de Belize",
    "CAD": "Dólar canadense",
    "CDF": "Franco congolês",
    "CHF": "Franco suíço",
    "CLP": "Peso chileno",
    "CNY": "Yuan chinês",
    "COP": "Peso colombiano",
    "CRC": "Colón costarriquenho",
    "CUP": "Peso cubano",
    "CVE": "Escudo cabo-verdiano",
    "CZK": "Coroa tcheca",
    "DJF": "Franco djibutiano",
    "DKK": "Coroa dinamarquesa",
    "DOP": "Peso dominicano",
    "DZD": "Dinar argelino",
    "EGP": "Libra egípcia",
    "ERN": "Nakfa eritreu",
    "ETB": "Birr etíope",
    "EUR": "Euro",
    "FJD": "Dólar fijiano",
    "FKP": "Libra das Ilhas Malvinas",
    "FOK": "Coroa feroesa",
    "GBP": "Libra esterlina",
    "GEL": "Lari georgiano",
    "GGP": "Libra de Guernsey",
    "GHS": "Cedi ganês",
    "GIP": "Libra de Gibraltar",
    "GMD": "Dalasi gambiano",
    "GNF": "Franco guineano",
    "GTQ": "Quetzal guatemalteco",
    "GYD": "Dólar guianense",
    "HKD": "Dólar de Hong Kong",
    "HNL": "Lempira hondurenha",
    "HRK": "Kuna croata",
    "HTG": "Gourde haitiano",
    "HUF": "Forint húngaro",
    "IDR": "Rupia indonésia",
    "ILS": "Novo shekel israelense",
    "IMP": "Libra de Man",
    "INR": "Rupia indiana",
    "IQD": "Dinar iraquiano",
    "IRR": "Rial iraniano",
    "ISK": "Coroa islandesa",
    "JEP": "Libra de Jersey",
    "JMD": "Dólar jamaicano",
    "JOD": "Dinar jordaniano",
    "JPY": "Iene japonês",
    "KES": "Xelim queniano",
    "KGS": "Som quirguiz",
    "KHR": "Riel cambojano",
    "KID": "Dólar de Kiribati",
    "KMF": "Franco comoriano",
    "KRW": "Won sul-coreano",
    "KWD": "Dinar kuwaitiano",
    "KYD": "Dólar das Ilhas Cayman",
    "KZT": "Tenge cazaque",
    "LAK": "Kip laosiano",
    "LBP": "Libra libanesa",
    "LKR": "Rupia do Sri Lanka",
    "LRD": "Dólar liberiano",
    "LSL": "Loti do Lesoto",
    "LYD": "Dinar líbio",
    "MAD": "Dirham marroquino",
    "MDL": "Leu moldavo",
    "MGA": "Ariary malgaxe",
    "MKD": "Denar macedônio",
    "MMK": "Kyat birmanês",
    "MNT": "Tugrik mongol",
    "MOP": "Pataca macaense",
    "MRU": "Ouguiya mauritana",
    "MUR": "Rupia mauriciana",
    "MVR": "Rufiyaa maldiva",
    "MWK": "Kwacha malauiano",
    "MXN": "Peso mexicano",
    "MYR": "Ringgit malaio",
    "MZN": "Metical moçambicano",
    "NAD": "Dólar namibiano",
    "NGN": "Naira nigeriana",
    "NIO": "Córdoba nicaraguense",
    "NOK": "Coroa norueguesa",
    "NPR": "Rupia nepalesa",
    "NZD": "Dólar neozelandês",
    "OMR": "Rial omanense",
    "PAB": "Balboa panamenho",
    "PEN": "Sol peruano",
    "PGK": "Kina papuásia",
    "PHP": "Peso filipino",
    "PKR": "Rupia paquistanesa",
    "PLN": "Zloty polonês",
    "PYG": "Guarani paraguaio",
    "QAR": "Rial catariano",
    "RON": "Leu romeno",
    "RSD": "Dinar sérvio",
    "RUB": "Rublo russo",
    "RWF": "Franco ruandês",
    "SAR": "Rial saudita",
    "SBD": "Dólar das Ilhas Salomão",
    "SCR": "Rupia seichelense",
    "SDG": "Libra sudanesa",
    "SEK": "Coroa sueca",
    "SGD": "Dólar de Singapura",
    "SHP": "Libra de Santa Helena",
    "SLE": "Leone da Serra Leoa",
    "SLL": "Leone da Serra Leoa (antigo)",
    "SOS": "Xelim somali",
    "SRD": "Dólar surinamês",
    "SSP": "Libra sul-sudanesa",
    "STN": "Dobra de São Tomé e Príncipe",
    "SYP": "Libra síria",
    "SZL": "Lilangeni suazi",
    "THB": "Baht tailandês",
    "TJS": "Somoni tadjique",
    "TMT": "Manat turcomeno",
    "TND": "Dinar tunisiano",
    "TOP": "Paʻanga tonganês",
    "TRY": "Lira turca",
    "TTD": "Dólar de Trinidad e Tobago",
    "TVD": "Dólar tuvaluano",
    "TWD": "Novo dólar taiwanês",
    "TZS": "Xelim tanzaniano",
    "UAH": "Hryvnia ucraniana",
    "UGX": "Xelim ugandense",
    "USD": "Dólar americano",
    "UYU": "Peso uruguaio",
    "UZS": "Som uzbeque",
    "VES": "Bolívar venezuelano",
    "VND": "Dong vietnamita",
    "VUV": "Vatu vanuatuense",
    "WST": "Tala samoano",
    "XAF": "Franco CFA da África Central",
    "XCD": "Dólar do Caribe Oriental",
    "XCG": "Moeda desconhecida",
    "XDR": "Direitos Especiais de Saque (SDR)",
    "XOF": "Franco CFA da África Ocidental",
    "XPF": "Franco CFP",
    "YER": "Rial iemenita",
    "ZAR": "Rand sul-africano",
    "ZMW": "Kwacha zambiano",
    "ZWL": "Dólar do Zimbábue"
}


sigla = input("\nDigite a sigla da moeda que deseja: ").upper()


url = "https://api.exchangerate-api.com/v4/latest/BRL"
response = requests.get(url)

if response.status_code == 200:
    dados = response.json()


    if sigla in dados["rates"]:
        cotacao = dados["rates"][sigla]


        nome_moeda = moedas.get(sigla, sigla)

        print(f"O Real vale {cotacao:.2f} {nome_moeda}.")
    else:
        print("Moeda não encontrada na base de dados da API.")
else:
    print("Erro ao acessar a API. Verifique sua conexão com a internet.")